export const FETCH_RECENT_RECIPES_REQUEST = 'FETCH_RECENT_RECIPES_REQUEST';
export const FETCH_RECENT_RECIPES_SUCCESS = 'FETCH_RECENT_RECIPES_SUCCESS';
export const FETCH_RECENT_RECIPES_FAILURE = 'FETCH_RECENT_RECIPES_FAILURE';
